// <auto-generated />
using System;
using KolokwiumPoprawa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KolokwiumPoprawa.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220628164742_M")]
    partial class M
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolokwiumPoprawa.Models.File", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.HasIndex("TeamID");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            FileID = 1,
                            FileExtension = "ext1",
                            FileName = "File1",
                            FileSize = 123,
                            TeamID = 1
                        },
                        new
                        {
                            FileID = 2,
                            FileExtension = "ext1",
                            FileName = "File2",
                            FileSize = 334,
                            TeamID = 2
                        },
                        new
                        {
                            FileID = 3,
                            FileExtension = "ext2",
                            FileName = "File3",
                            FileSize = 153,
                            TeamID = 1
                        },
                        new
                        {
                            FileID = 4,
                            FileExtension = "ext2",
                            FileName = "File4",
                            FileSize = 653,
                            TeamID = 2
                        },
                        new
                        {
                            FileID = 5,
                            FileExtension = "ext4",
                            FileName = "File5",
                            FileSize = 113,
                            TeamID = 3
                        },
                        new
                        {
                            FileID = 6,
                            FileExtension = "ext2",
                            FileName = "File6",
                            FileSize = 53,
                            TeamID = 4
                        },
                        new
                        {
                            FileID = 7,
                            FileExtension = "ext2",
                            FileName = "File7",
                            FileSize = 23,
                            TeamID = 1
                        },
                        new
                        {
                            FileID = 8,
                            FileExtension = "ext1",
                            FileName = "File8",
                            FileSize = 1223,
                            TeamID = 1
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberNickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            MemberName = "MemberName 1",
                            MemberSurname = "MemberSurname 1",
                            OrganizationID = 1
                        },
                        new
                        {
                            MemberID = 2,
                            MemberName = "MemberName 2",
                            MemberSurname = "MemberSurname 2",
                            OrganizationID = 1
                        },
                        new
                        {
                            MemberID = 3,
                            MemberName = "MemberName 3",
                            MemberSurname = "MemberSurname 3",
                            OrganizationID = 2
                        },
                        new
                        {
                            MemberID = 4,
                            MemberName = "MemberName 4",
                            MemberSurname = "MemberSurname 4",
                            OrganizationID = 2
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Membership", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            TeamID = 1,
                            MembershipDate = new DateTime(2012, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 1,
                            MembershipDate = new DateTime(2011, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 3,
                            TeamID = 2,
                            MembershipDate = new DateTime(2014, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 4,
                            TeamID = 3,
                            MembershipDate = new DateTime(2005, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 3,
                            TeamID = 3,
                            MembershipDate = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 4,
                            MembershipDate = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationDomain")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationDomain = "OrganizationDomain 1",
                            OrganizationName = "OrganizationName 1"
                        },
                        new
                        {
                            OrganizationID = 2,
                            OrganizationDomain = "OrganizationDomain 2",
                            OrganizationName = "OrganizationName 2"
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            OrganizationID = 1,
                            TeamDescription = "Desc 1",
                            TeamName = "Team Name 1"
                        },
                        new
                        {
                            TeamID = 2,
                            OrganizationID = 1,
                            TeamDescription = "Desc 2",
                            TeamName = "Team Name 2"
                        },
                        new
                        {
                            TeamID = 3,
                            OrganizationID = 2,
                            TeamDescription = "Desc 3",
                            TeamName = "Team Name 3"
                        },
                        new
                        {
                            TeamID = 4,
                            OrganizationID = 2,
                            TeamDescription = "Desc 4",
                            TeamName = "Team Name 4"
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.File", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Team", "Team")
                        .WithMany("Files")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Membership", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KolokwiumPoprawa.Models.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
